In [2]:
from struct import Struct
fieldwidths = (2, -10, 24)  # negative widths represent ignored padding fields
fmtstring = ' '.join('{}{}'.format(abs(fw), 'x' if fw < 0 else 's')
                     for fw in fieldwidths)
print(fmtstring)
fieldstruct = Struct(fmtstring)
unpack = fieldstruct.unpack_from

def parse(line): return tuple(s.decode() for s in unpack(line.encode()))

file = open("fixedwidth.txt", "r")
for line in file: 
    print(parse(line))
    

2s 10x 24s


error: unpack_from requires a buffer of at least 36 bytes

In [6]:
import numpy as np
from io import StringIO
data = u"123456789\n   4  7 9\n   4567 9"
np.genfromtxt(StringIO(data), delimiter=(4, 3, 2))


array([[1234.,  567.,   89.],
       [   4.,    7.,    9.],
       [   4.,  567.,    9.]])

In [7]:
file = open("fixedwidth.txt", "r")
converted = np.genfromtxt(file, delimiter=(4,-3,2, 6))
file.close()
converted

array([[0.00000e+00,         nan, 0.00000e+00, 0.00000e+00],
       [1.23000e+02,         nan, 1.20000e+01, 3.45678e+05]])

In [8]:
file = open("commas.csv", "r")
converted = np.genfromtxt(file, delimiter=',', invalid_raise=False)
file.close()
converted

/home/singhj/anaconda3/envs/comp205/lib/python3.7/site-packages/ipykernel_launcher.py:2: ConversionWarning: Some errors were detected !
    Line #2 (got 5 columns instead of 4)
  


array([[ 1.,  2., nan,  3.],
       [ 7.,  8., nan,  9.]])

This is a test. 
<font color='red'> 
This is another. 
</font> 

In [1]:
from colorama import Fore
print("ho ho ho {} {} {}".format(Fore.RED, "foo", Fore.BLACK))
print("you")

ModuleNotFoundError: No module named 'colorama'

In [3]:
print(Fore.GREEN)
print("This is a test")


This is a test


In [4]:
print ("ho")

ho
